urls.py
from django.conf.urls import include,patterns, url
from django.conf.urls.static import static
from django.conf import settings
from ceqanet.views import index,basicsearch,advancedsearch,prjlist,doclist,projectlist,projdoclist,submit,draftsbylag,pendingsbylag,chquery,findproject,accept,usersettings,attachments,manageaccount,requestupgrd,manageupgrades,manageupgrade,manageusers,manageuser,reviewsbylag
from ceqanet.views import docdesp_noc,docdesp_noe,docdesp_nod,docdesp_nop
from ceqanet.views import docadd_noc,docadd_nod,docadd_noe,docadd_nop
from ceqanet.views import docedit_noc,docedit_noe,docedit_nod,docedit_nop
from ceqanet.views import draftedit_noc,draftedit_nod,draftedit_noe,draftedit_nop
from ceqanet.views import pending,pendingdetail_noc,pendingdetail_nod,pendingdetail_noe,pendingdetail_nop,latest,addleadagency,addreviewingagency,addholiday
from ceqanet.views import review,reviewdetail_noc,reviewdetail_nop
from ceqanet.views import comment,commentdetail,commentadd,showcomment,commentaccept
#map related views
from ceqanet.views import locations_geojson, map, locationEdit
#document api
from ceqanet.views import doc_json,doc_location
#from registration.backends.default.views import register
#from ceqanet.forms import UserRegistrationForm
#import regbackend

urlpatterns = patterns('ceqanet.views',
    url(r'^$','index',name='index'),
    url(r'^search/$',basicsearch.as_view(),name='basicsearch'),
    url(r'^search/advanced/$',advancedsearch.as_view(),name='advancedsearch'),
    url(r'^project/list/$',prjlist.as_view(),name='prjlist'),
    url(r'^document/list/$',doclist.as_view(),name='doclist'),
    url(r'^projectlist/$',projectlist.as_view(),name='projectlist'),
    url(r'^projdoclist/$',projdoclist.as_view(),name='projdoclist'),
    url(r'^submit/$',submit.as_view(),name='submit'),
    url(r'^draftsbylag/$',draftsbylag.as_view(),name='draftsbylag'),
    url(r'^pendingsbylag/$',pendingsbylag.as_view(),name='pendingsbylag'),
    url(r'^reviewsbylag/$',reviewsbylag.as_view(),name='reviewsbylag'),
    url(r'^accept/$','accept',name='accept'),
    url(r'^chquery/$',chquery.as_view(),name='chquery'),
    url(r'^project/find$',findproject.as_view(),name='findproject'),
    url(r'^attachments/$',attachments.as_view(),name='attachments'),
    url(r'^draft/noc/edit/$',draftedit_noc.as_view(),name='draftedit_noc'),
    url(r'^draft/nod/edit/$',draftedit_nod.as_view(),name='draftedit_nod'),
    url(r'^draft/noe/edit/$',draftedit_noe.as_view(),name='draftedit_noe'),
    url(r'^draft/nop/edit/$',draftedit_nop.as_view(),name='draftedit_nop'),
    url(r'^document/noc/description/(?P<pk>\d+)/$',docdesp_noc.as_view(),name='docdesp_noc'),
    url(r'^document/nod/description/(?P<pk>\d+)/$',docdesp_nod.as_view(),name='docdesp_nod'),
    url(r'^document/noe/description/(?P<pk>\d+)/$',docdesp_noe.as_view(),name='docdesp_noe'),
    url(r'^document/nop/description/(?P<pk>\d+)/$',docdesp_nop.as_view(),name='docdesp_nop'),
    url(r'^document/noc/edit/$',docedit_noc.as_view(),name='docedit_noc'),
    url(r'^document/nod/edit/$',docedit_nod.as_view(),name='docedit_nod'),
    url(r'^document/noe/edit/$',docedit_noe.as_view(),name='docedit_noe'),
    url(r'^document/nop/edit/$',docedit_nop.as_view(),name='docedit_nop'),
    url(r'^document/noc/add/$',docadd_noc.as_view(),name='docadd_noc'),
    url(r'^document/nod/add/$',docadd_nod.as_view(),name='docadd_nod'),
    url(r'^document/noe/add/$',docadd_noe.as_view(),name='docadd_noe'),
    url(r'^document/nop/add/$',docadd_nop.as_view(),name='docadd_nop'),
    url(r'^document/showcomment/(?P<pk>\d+)/$',showcomment.as_view(),name='showcomment'),    
    url(r'^pending/$',pending.as_view(),name='pending'),
    url(r'^latest/$',latest.as_view(),name='latest'),
    url(r'^addleadagency/$',addleadagency.as_view(),name='addleadagency'),
    url(r'^addreviewingagency/$',addreviewingagency.as_view(),name='addreviewingagency'),
    url(r'^addholiday/$',addholiday.as_view(),name='addholiday'),
    url(r'^review/$',review.as_view(),name='review'),
    url(r'^pending/noc/detail/$',pendingdetail_noc.as_view(),name='pendingdetail_noc'),
    url(r'^pending/nod/detail/$',pendingdetail_nod.as_view(),name='pendingdetail_nod'),
    url(r'^pending/noe/detail/$',pendingdetail_noe.as_view(),name='pendingdetail_noe'),
    url(r'^pending/nop/detail/$',pendingdetail_nop.as_view(),name='pendingdetail_nop'),
    url(r'^review/$',review.as_view(),name='review'),
    url(r'^review/noc/detail/$',reviewdetail_noc.as_view(),name='reviewdetail_noc'),
    url(r'^review/nop/detail/$',reviewdetail_nop.as_view(),name='reviewdetail_nop'),
    url(r'^comment/$',comment.as_view(),name='comment'),
    url(r'^comment/detail/$',commentdetail.as_view(),name='commentdetail'),
    url(r'^comment/add/$',commentadd.as_view(),name='commentadd'),
    url(r'^comment/accept/$','commentaccept',name='commentaccept'),
    url(r'^user/account/$',manageaccount.as_view(),name='manageaccount'),
    url(r'^user/requestupgrade/$',requestupgrd.as_view(),name='requestupgrd'),
    url(r'^user/manageupgrades/$',manageupgrades.as_view(),name='manageupgrades'),
    url(r'^user/manageupgrade/$',manageupgrade.as_view(),name='manageupgrade'),
    url(r'^user/manageusers/$',manageusers.as_view(),name='manageusers'),
    url(r'^user/manageuser/$',manageuser.as_view(),name='manageuser'),
    url(r'^user/settings/$',usersettings.as_view(),name='usersettings'),
    url(r'^county/(?P<county>[-\w]+)/citiesforcounty_json/$', 'citiesforcounty_json'),
    url(r'^map/all/geojson/$','locations_geojson',name="locationsall"),
    url(r'^map/all/geojson/(?P<limit>\d+)/$','locations_geojson',name="locationslimited"),
    url(r'^api/doc/short/(?P<doc_id>\d+)/$','doc_json',name="doc_json"),
    url(r'^api/doc/location/(?P<doc_id>\d+)/$','doc_location',name="doc_location"), 
    url(r'^map/$','map',name="map"),
    url(r'^document/location/edit/(?P<slug>\d+)/$',locationEdit.as_view(),name='map_edit'),
) 
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += patterns('',
    #url(r'^accounts/register/$', register, {'backend': 'registration.backends.default.DefaultBackend','form_class': UserRegistrationForm}, name='registration_register'),    
    url(r'^accounts/login/$','django.contrib.auth.views.login',{'template_name':'ceqanet/login.html'},name = 'login'),
    #url(r'^accounts/login/$','django.contrib.auth.views.login',name = 'login'),
    url(r'^accounts/logout/$','django.contrib.auth.views.logout', {'next_page': '/'}, name = 'logout'),
)

#urlpatterns = patterns('',
#    ...
#    (r'^accounts/', include('allauth.urls')),
#    ...
#)

forms.py
from django import forms
from django.forms import ModelForm
from olwidget.forms import  MapModelForm
from olwidget.fields import EditableLayerField
from olwidget.widgets import EditableMap
from datetime import datetime, date, timedelta
from django.contrib.auth.models import Group
from ceqanet.models import projects,documents,geowords,reviewingagencies,leadagencies,keywords,doctypes,docattachments,Locations,holidays
from localflavor.us.forms import USPhoneNumberField,USStateField,USZipCodeField
from enumerations import DOCUMENT_TYPES,PROJECT_EXISTS,EXEMPT_STATUS_CHOICES,PLANNERREGION_CHOICES,COLATION_CHOICES,PRJ_SORT_FIELDS,DOC_SORT_FIELDS,RDODATE_CHOICES,RDOPLACE_CHOICES,RDOLAG_CHOICES,RDORAG_CHOICES,RDODOCTYPE_CHOICES,DETERMINATION_CHOICES,NODAGENCY_CHOICES,RDOLAT_CHOICES,RDODEVTYPE_CHOICES,RDOISSUE_CHOICES,RDOTITLE_CHOICES,RDODESCRIPTION_CHOICES,UPGRADE_CHOICES,COMMENT_CHOICES,NODFEESPAID_CHOICES
from django.contrib.admin.widgets import FilteredSelectMultiple

class MapForm(forms.Form):
    '''Reusable Map enhancement to forms, inherited by document forms needing location entry'''
    geom = forms.CharField(label="Geography:",widget=EditableMap(options={'layers': ['osm.mapnik'],
                                                    'isCollection':True, 
                                                    'geometry':['point','polygon'],
                                                    'default_lat': 37.424431833728114,
                                                    'default_lon': -121.90515908415186,'default_zoom':6},template=None))
    
class basicsearchform(forms.Form):
    prj_schno = forms.CharField(label="Clearinghouse Number:",required=True,max_length=12)
    colation = forms.ChoiceField(label="Search Database By:",required=True,choices=COLATION_CHOICES,initial='document',widget=forms.RadioSelect())

class advancedsearchform(forms.Form):
    rdodate = forms.ChoiceField(label="Date Range:",required=True,choices=RDODATE_CHOICES,initial='range',widget=forms.RadioSelect(attrs={'id':'rdodate'}))
    date_from = forms.DateField(label="From:",required=False, initial=lambda: (date.today() - timedelta(days=180)).strftime("%Y-%m-%d"),input_formats=['%Y-%m-%d'])
    date_to = forms.DateField(label="To:",required=False, initial=date.today().strftime("%Y-%m-%d"),input_formats=['%Y-%m-%d'])
    rdoplace = forms.ChoiceField(label="Project Location:",required=True,choices=RDOPLACE_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdoplace'}))
    cityid = forms.ModelChoiceField(label="City:",required=False,queryset=geowords.objects.filter(geow_geol_fk=1002).filter(inlookup=True).order_by('geow_shortname'),empty_label=None)
    countyid = forms.ModelChoiceField(label="County:",required=False,queryset=geowords.objects.filter(geow_geol_fk=1001).filter(inlookup=True).order_by('geow_shortname'),empty_label=None)
    rdolag = forms.ChoiceField(label="Lead Agency:",required=True,choices=RDOLAG_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdolag'}))
    lagid = forms.ModelChoiceField(label="Lead Agency:",required=False,queryset=leadagencies.objects.filter(inlookup=True).order_by('lag_name'),empty_label=None)
    rdorag = forms.ChoiceField(label="Reviewing Agency:",required=True,choices=RDORAG_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdorag'}))
    ragid = forms.ModelChoiceField(label="Reviewing Agency:",required=False,queryset=reviewingagencies.objects.filter(inlookup=True).order_by('rag_name'),empty_label=None)
    rdodoctype = forms.ChoiceField(label="Document Type:",required=True,choices=RDODOCTYPE_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdodoctype'}))
    doctypeid = forms.ModelChoiceField(label="Document Type:",required=False,queryset=doctypes.objects.filter(inlookup=True).order_by('keyw_longname'),empty_label=None)
    rdolat = forms.ChoiceField(label="Local Action Type:",required=True,choices=RDOLAT_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdolat'}))
    latid = forms.ModelChoiceField(label="Local Action Type:",required=False,queryset=keywords.objects.filter(keyw_keyl_fk__keyl_pk=1001).order_by('keyw_longname'),empty_label=None)
    rdodevtype = forms.ChoiceField(label="Development Type:",required=True,choices=RDODEVTYPE_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdodevtype'}))
    devtypeid = forms.ModelChoiceField(label="Development Type:",required=False,queryset=keywords.objects.filter(keyw_keyl_fk__keyl_pk=1010).order_by('keyw_longname'),empty_label=None)
    rdoissue = forms.ChoiceField(label="Project Issue:",required=True,choices=RDOISSUE_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdoissue'}))
    issueid = forms.ModelChoiceField(label="Project Issue:",required=False,queryset=keywords.objects.filter(keyw_keyl_fk__keyl_pk=1002).order_by('keyw_longname'),empty_label=None)
    rdotitle = forms.ChoiceField(label="Project Title Contains:",required=True,choices=RDOTITLE_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdotitle'}))
    titlestr = forms.CharField(label="Project Title Contains:",required=False,max_length=100,widget=forms.TextInput(attrs={'size':'64'}))
    rdodescription = forms.ChoiceField(label="Project Description Contains:",required=True,choices=RDODESCRIPTION_CHOICES,initial='all',widget=forms.RadioSelect(attrs={'id':'rdodescription'}))
    descriptionstr = forms.CharField(label="Project Description Contains:",required=False,max_length=100,widget=forms.TextInput(attrs={'size':'64'}))
    colation = forms.ChoiceField(label="Search Database By:",required=True,choices=COLATION_CHOICES,initial='document',widget=forms.RadioSelect(attrs={'id':'colation'}))

class prjlistform(forms.Form):
    sortfld = forms.ChoiceField(label="Sort Results By:",required=True,choices=PRJ_SORT_FIELDS,initial='-prj_schno')

class doclistform(forms.Form):
    sortfld = forms.ChoiceField(label="Sort Results By:",required=True,choices=DOC_SORT_FIELDS,initial='-doc_prj_fk__prj_schno')

class submitform(forms.Form):
    doctype = forms.ChoiceField(required=True,choices=DOCUMENT_TYPES,initial='NOC')
    prjtoggle = forms.ChoiceField(required=True,choices=PROJECT_EXISTS,initial='no',widget=forms.RadioSelect(attrs={'id':'prjtoggle','class':'prjtoggle'}))

class basedocumentform(MapForm):
    prj_title = forms.CharField(label="Project Title:",required=True,max_length=160,widget=forms.Textarea(attrs={'cols':'75','rows':'2'}))
    prj_description = forms.CharField(label="Project Description:",required=True,widget=forms.Textarea(attrs={'cols':'75','rows':'5'}))
    doc_title = forms.CharField(label="Alternate Title:",required=False,widget=forms.Textarea(attrs={'cols':'75','rows':'2'}))
    doc_description = forms.CharField(label="Alternate Description:",required=False,widget=forms.Textarea(attrs={'cols':'75','rows':'5'}))
    doc_conname = forms.CharField(label="Contact Person:",required=True,max_length=64,widget=forms.TextInput(attrs={'size':'50'}))
    doc_conemail = forms.EmailField(label="E-mail:",required=True,max_length=64,widget=forms.TextInput(attrs={'size':'50'}))
    doc_conphone = USPhoneNumberField(label="Phone:",required=True)
    doc_conaddress1 = forms.CharField(label="Street Address1:",required=True,max_length=64,widget=forms.TextInput(attrs={'size':'50'}))
    doc_conaddress2 = forms.CharField(label="Street Address2:",required=False,max_length=64,widget=forms.TextInput(attrs={'size':'50'}))
    doc_concity = forms.CharField(label="City:",required=True,max_length=32,widget=forms.TextInput(attrs={'size':'32'}))
    doc_constate = USStateField(label="State:",required=True)
    doc_conzip = USZipCodeField(label="Zip:",required=True)
    doc_location = forms.CharField(label="Document Location:",required=False,widget=forms.Textarea(attrs={'cols':'75','rows':'2'}))
    doc_latitude = forms.FloatField(label="Latitude:",required=True,widget=forms.TextInput(attrs={'size':'30'}))
    doc_longitude = forms.FloatField(label="Longitude:",required=True,widget=forms.TextInput(attrs={'size':'30'}))
    counties = forms.ModelMultipleChoiceField(label="Counties:",required=False,queryset=geowords.objects.filter(geow_geol_fk=1001).filter(inlookup=True).order_by('geow_shortname'),widget=forms.SelectMultiple(attrs={'size':'8'}))
    cities = forms.ModelMultipleChoiceField(label="Cities:",required=False,queryset=geowords.objects.filter(geow_geol_fk=1002).filter(inlookup=True).order_by('geow_shortname'),widget=forms.SelectMultiple(attrs={'size':'8'}))
    statewide = forms.ChoiceField(required=True,choices=PROJECT_EXISTS,initial='no',widget=forms.RadioSelect(attrs={'id':'statewide','class':'statewide'}))

    def clean(self):
        cleaned_data = super(basedocumentform, self).clean()

        msg_countyerror = u"County is Required."

        if cleaned_data.get('statewide') == 'no':
            if cleaned_data.get('counties') == None:
                self._errors['counties'] = self.error_class([msg_countyerror])
                del cleaned_data['counties']

        msg_cityerror = u"City Not Within County Specified: "

        if cleaned_data.get('cities') != None:
            if cleaned_data.get('counties') != None:
                for cty in cleaned_data.get('cities'):
                    if cty.geow_parent_fk not in cleaned_data.get('counties'):
                        self._errors['cities'] = self.error_class([msg_cityerror + cty.geow_shortname])
                        del cleaned_data['cities']
        return cleaned_data

class nodform(basedocumentform):
    leadorresp = forms.ChoiceField(required=True,choices=NODAGENCY_CHOICES,widget=forms.RadioSelect(attrs={'id':'lorr','class':'lorr'}))
    doc_nodagency = forms.ModelChoiceField(required=True,queryset=leadagencies.objects.filter(inlookup=True).order_by('lag_name'),empty_label="[Select Agency]",widget=forms.Select(attrs={'id':'nodagency','class':'nodagency'}))
    #leadorresp = forms.CharField(required=True,max_length=10,widget=forms.HiddenInput())

templates/ceqanet/advancedsearch.html
{% extends "ceqanet/base.html" %}

{% block title %}OPR Data Clearinghouse Search{% endblock title %}

{% block extrajs %}
  <script>
    $(function() {
        $( "#id_date_from" ).datepicker({dateFormat: "yy-mm-dd"});
    });
    $(function() {
        $( "#id_date_to" ).datepicker({dateFormat: "yy-mm-dd"});
    });
  </script>
{% endblock extrajs %}

{% block content %}

<table>
    <tr>
      <td colspan="3">
        <h4>Advanced Search</h4>
      </td>
    </tr>
    <tr>
      <td colspan="3" align="right">
        <button onclick="window.location = '{% url 'basicsearch' %}'">Basic Search</button>
      </td>
    </tr>
  <FORM name="searchform" method="post" action="">
    {% csrf_token %}
    <tr>
      <td colspan="3">
        <b>{{ form.colation.label }}</b>
        {% for r in form.colation %}
          {{ r }}
        {% endfor %}
      </td>
    </tr>
    <tr>
      <td>
        &nbsp;
      </td>
    </tr>
    <tr>
      <td>
        <B><FONT size="+1">Apply Search Filters:</FONT></B>
      </td>
    </tr>
    <tr>
      <td>
        &nbsp;
      </td>
    </tr>
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdodate.label }}
      </TH>
    </tr>
    {% for date in form.rdodate %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ date }}
      {% else %}
        <div id="rdodate_div">
          {{ date }} {{ form.date_from.label }} {{ form.date_from }} {{ form.date_to.label }} {{ form.date_to }}
        </div>
        <input type="button" id="days30" value="Previous 30 Days">
        <input type="button" id="days60" value="Previous 60 Days">
        <input type="button" id="days90" value="Previous 90 Days">
        <input type="button" id="days180" value="Previous 180 Days">
        <input type="button" id="days360" value="Previous 360 Days">
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <script>
      $(document).ready(function() {
        function setdatepickers(days) {
          var today = new Date();
          var past = new Date();
          past.setDate(today.getDate()-days);
          $("#id_date_from").datepicker().datepicker('setDate',past);
          $("#id_date_to").datepicker().datepicker('setDate',today);
        };
        $("#days30").click(function() {setdatepickers(30);});
        $("#days60").click(function() {setdatepickers(60);});
        $("#days90").click(function() {setdatepickers(90);});
        $("#days180").click(function() {setdatepickers(180);});
        $("#days360").click(function() {setdatepickers(360);});
      });
    </script>
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdoplace.label }}
      </TH>
    </tr>
    {% for place in form.rdoplace %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ place }}
      {% elif forloop.counter = 2 %}
        <div id="rdoplace1_div">
          {{ place }} {{ form.cityid }}
        </div>
      {% elif forloop.counter = 3 %}
        <div id="rdoplace2_div">
          {{ place }} {{ form.countyid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdolag.label }}
      </TH>
    </tr>
    {% for lag in form.rdolag %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ lag }}
      {% elif forloop.counter = 2 %}
        <div id="rdolag_div">
          {{ lag }} {{ form.lagid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdorag.label }}
      </TH>
    </tr>
    {% for rag in form.rdorag %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ rag }}
      {% elif forloop.counter = 2 %}
        <div id="rdorag_div">
          {{ rag }} {{ form.ragid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdodoctype.label }}
      </TH>
    </tr>
    {% for doctype in form.rdodoctype %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ doctype }}
      {% elif forloop.counter = 2 %}
        <div id="rdodoctype_div">
          {{ doctype }} {{ form.doctypeid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdolat.label }}
      </TH>
    </tr>
    {% for lat in form.rdolat %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ lat }}
      {% elif forloop.counter = 2 %}
        <div id="rdolat_div">
          {{ lat }} {{ form.latid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdodevtype.label }}
      </TH>
    </tr>
    {% for devtype in form.rdodevtype %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ devtype }}
      {% elif forloop.counter = 2 %}
        <div id="rdodevtype_div">
          {{ devtype }} {{ form.devtypeid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdoissue.label }}
      </TH>
    </tr>
    {% for issue in form.rdoissue %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ issue }}
      {% elif forloop.counter = 2 %}
        <div id="rdoissue_div">
          {{ issue }} {{ form.issueid }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdotitle.label }}
      </TH>
    </tr>
    {% for title in form.rdotitle %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ title }}
      {% elif forloop.counter = 2 %}
        <div id="rdotitle_div">
          {{ title }} {{ form.titlestr }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <TH colspan="3" align="left">
        {{ form.rdodescription.label }}
      </TH>
    </tr>
    {% for description in form.rdodescription %}
    <TR>
      <TD colspan="3">
      {% if forloop.counter = 1 %}
        {{ description }}
      {% elif forloop.counter = 2 %}
        <div id="rdodescription_div">
          {{ description }} {{ form.descriptionstr }}
        </div>
      {% endif %}
      </TD>
    </TR>
    {% endfor %}
    <tr>
      <td>
        &nbsp;
      </td>
    </tr>
    <tr>
      <td colspan="3">
        <input type="submit" value="Submit Search">
      </td>
    </tr>
  </form>
</table>

<script>
  $("#rdodate_div").click(function() {
    setRadio('rdodate_1');
  });
  $("#rdoplace1_div").click(function() {
    setRadio('rdoplace_1');
  });
  $("#rdoplace2_div").click(function() {
    setRadio('rdoplace_2');
  });
  $("#rdolag_div").click(function() {
    setRadio('rdolag_1');
  });
  $("#rdorag_div").click(function() {
    setRadio('rdorag_1');
  });
  $("#rdodoctype_div").click(function() {
    setRadio('rdodoctype_1');      
  });
  $("#rdolat_div").click(function() {
    setRadio('rdolat_1');      
  });
  $("#rdodevtype_div").click(function() {
    setRadio('rdodevtype_1');      
  });
  $("#rdoissue_div").click(function() {
    setRadio('rdoissue_1');      
  });
  $("#rdotitle_div").click(function() {
    setRadio('rdotitle_1');      
  });
  $("#rdodescription_div").click(function() {
    setRadio('rdodescription_1');      
  });
  
  function setRadio(id) {
    var radio = $('#' + id);
    radio[0].checked = true;
    radio.button("refresh");
  }
</script>

{% endblock content %}

templates/ceqanet/commentaccept.html
{% extends "ceqanet/base.html" %}

{% load staticfiles %}

{% block content %}
    
  <table border="0" cellpadding="5">
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>
        <B>Official CEQA Comment attached to Document. Thank you.</B>
      </td>
    </tr>
    <tr>
      <td>
        A confirmation e-mail has been sent to the reviewers belonging to this Reviewing Agency, as well as the Lead Agency cited in the Document commented on.
      </td>
    </tr>
  </table>

{% endblock content %}

templates/ceqanet/listpage.html
{% extends "ceqanet/base.html"%}

{% block content %}
<div class='listing'>
  {% block listing %}
  {% endblock %}
</div>
{% endblock %}